/// CryptoLib for Flutter — public API.
///
/// `CryptoLib` is the entry point. The native library loads lazily on first use;
/// call `CryptoLib.preload()` once at app start to warm it off the UI isolate.
///
/// The crypto operations live on domain extensions of `CryptoLib` (hashing,
/// symmetric, asymmetric, vault, keyring, post-quantum, BLS, asymmetric vault,
/// media entropy, steganography) — all are re-exported here, so a single
/// `import 'package:cryptolib_flutter/cryptolib_flutter.dart';` brings the full
/// surface into scope. The raw FFI structs/typedefs stay internal.
library;

export 'src/cryptolib.dart'
    show
        AeadApi,
        AsymApi,
        AsymBundleResult,
        BbsApi,
        BlsApi,
        ChainApi,
        ComposedApi,
        CryptoLib,
        CryptoLibAsymmetric,
        CryptoLibAsymmetricVault,
        CryptoLibBbs,
        CryptoLibBls,
        CryptoLibComposed,
        CryptoLibCore,
        CryptoLibEcvrf,
        CryptoLibEntropy,
        CryptoLibEntropyHealth,
        CryptoLibEvmBtc,
        CryptoLibFrost,
        CryptoLibHashing,
        CryptoLibHpke,
        CryptoLibKeyring,
        CryptoLibMolecular,
        CryptoLibNamespaces,
        CryptoLibOpaque,
        CryptoLibOprf,
        CryptoLibPostQuantum,
        CryptoLibRng,
        CryptoLibSealed,
        CryptoLibSession,
        CryptoLibStego,
        CryptoLibStegoAdvanced,
        CryptoLibSuite,
        CryptoLibSymmetric,
        CryptoLibVault,
        DerivedKeysResult,
        Drbg,
        EcvrfApi,
        EntropyApi,
        EntropyInfoResult,
        FecScheme,
        Fortuna,
        FrostApi,
        FrostCommitment,
        FrostKeyGen,
        FrostNonces,
        HashApi,
        HealthReport,
        HpkeAead,
        HpkeApi,
        HpkeContext,
        HpkeKdf,
        HpkeMode,
        HpkeSender,
        Identity,
        KeyPairResult,
        KeyringApi,
        MediaFormat,
        MlDsaLevel,
        MlKemLevel,
        OpaqueApi,
        OpaqueKe1,
        OpaqueKe2,
        OpaqueKe3,
        OpaqueRecord,
        OprfApi,
        OprfBlindResult,
        Packet,
        PqApi,
        PqHybridKemApi,
        PqHybridSigApi,
        PqMlDsaApi,
        PqMlKemApi,
        PqSlhDsaApi,
        PqSntrupApi,
        RngApi,
        SealedApi,
        SealedInfo,
        SealedStreamOpener,
        SealedStreamSealer,
        SealedTier,
        Session,
        SessionApi,
        SlhDsaHash,
        SlhDsaLevel,
        StegoApi,
        StegoFileInspection,
        StegoHiddenDataReport,
        SuiteApi,
        VaultApi;
