// KATs + round-trips for the EVM/BTC interop primitives:
// Keccak-256 (original padding), RIPEMD-160, and secp256k1 ECDSA.
#include "test_framework.hpp"

#include <cryptolib/keccak.hpp>
#include <cryptolib/ripemd160.hpp>
#include <cryptolib/secp256k1.hpp>

#include <array>
#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>
#include <vector>

#ifdef CRYPTOLIB_HAS_OPENSSL
// RIPEMD160() is deprecated in OpenSSL 3 but still exported; we use it only as
// an independent reference oracle in the differential test below.
#  pragma clang diagnostic push
#  pragma clang diagnostic ignored "-Wdeprecated-declarations"
#  include <openssl/ripemd.h>
#  pragma clang diagnostic pop
#endif

using crypto::SecureBuffer;

namespace {
// Decode a lowercase hex string into bytes.
std::vector<uint8_t> from_hex(std::string_view h) {
    auto nib = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        return 0;
    };
    std::vector<uint8_t> out;
    out.reserve(h.size() / 2);
    for (std::size_t i = 0; i + 1 < h.size(); i += 2)
        out.push_back(static_cast<uint8_t>((nib(h[i]) << 4) | nib(h[i + 1])));
    return out;
}
} // namespace

// ── Keccak-256 (original padding, NOT SHA3-256) ──────────────────────────────
TEST("evm/keccak256/empty-KAT") {
    auto r = crypto::hash::Keccak256::digest(std::string_view{""});
    CHECK_OK(r);
    CHECK(r.value().to_hex() ==
          "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470");
}

TEST("evm/keccak256/abc-KAT") {
    auto r = crypto::hash::Keccak256::digest(std::string_view{"abc"});
    CHECK_OK(r);
    CHECK(r.value().to_hex() ==
          "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45");
}

TEST("evm/keccak256/multi-block") {
    // 200 bytes > rate(136) exercises the multi-block absorb path.
    std::string msg(200, 'a');
    auto r = crypto::hash::Keccak256::digest(msg);
    CHECK_OK(r);
    CHECK(r.value().size() == 32);
}

// ── RIPEMD-160 ───────────────────────────────────────────────────────────────
TEST("btc/ripemd160/empty-KAT") {
    auto r = crypto::hash::Ripemd160::digest(std::string_view{""});
    CHECK_OK(r);
    CHECK(r.value().to_hex() == "9c1185a5c5e9fc54612808977ee8f548b2258d31");
}

TEST("btc/ripemd160/abc-KAT") {
    auto r = crypto::hash::Ripemd160::digest(std::string_view{"abc"});
    CHECK_OK(r);
    CHECK(r.value().to_hex() == "8eb208f7e05d987a9b044a8e98c6b087f15a0bfc");
}

TEST("btc/ripemd160/million-a-prefix") {
    // RIPEMD-160("a") known vector — exercises a non-empty single block.
    auto r = crypto::hash::Ripemd160::digest(std::string_view{"a"});
    CHECK_OK(r);
    CHECK(r.value().to_hex() == "0bdc9d2d256b3ee9daae347be6f4dc835a467ffe");
}

#ifdef CRYPTOLIB_HAS_OPENSSL
// Differential test: our standalone RIPEMD-160 must agree byte-for-byte with
// OpenSSL's audited implementation across every length / block boundary. This
// is far stronger than a couple of fixed KATs — it proves the padding, the
// 64-bit length encoding, and both compression lines on arbitrary inputs.
TEST("btc/ripemd160/differential-vs-openssl") {
    bool all_match = true;
    std::vector<uint8_t> buf;
    for (std::size_t len = 0; len <= 256; ++len) {
        buf.resize(len);
        for (std::size_t i = 0; i < len; ++i)
            buf[i] = static_cast<uint8_t>((i * 31 + len * 7 + 1) & 0xff);
        uint8_t ref[20];
        ::RIPEMD160(buf.data(), buf.size(), ref);
        auto mine = crypto::hash::Ripemd160::digest(buf);
        if (mine.is_err() || std::memcmp(mine.value().data(), ref, 20) != 0) {
            all_match = false;
            std::printf("      RIPEMD-160 mismatch at len=%zu\n", len);
            break;
        }
    }
    CHECK(all_match);
}
#endif

// Independent multi-length KATs: vectors generated by js-sha3 (a separate,
// widely-deployed Keccak implementation) over the input scheme byte[i]=i&0xff,
// covering the rate boundary (135/136/137) and beyond. These pin our output to
// an external reference offline — see scripts/keccak_cross_check.mjs for the
// live CI differential that regenerates and re-checks them.
TEST("evm/keccak256/multi-length-KAT") {
    struct V { std::size_t len; const char* hex; };
    static const V vecs[] = {
        {1,   "bc36789e7a1e281436464229828f817d6612f7b477d66591ff96a9e064bcc98a"},
        {32,  "8ae1aa597fa146ebd3aa2ceddf360668dea5e526567e92b0321816a4e895bd2d"},
        {135, "cbdfd9dee5faad3818d6b06f95a219fd290b0e1706f6a82e5a595b9ce9faca62"},
        {136, "7ce759f1ab7f9ce437719970c26b0a66ff11fe3e38e17df89cf5d29c7d7f807e"},
        {137, "ac73d4fae68b8453f764007c1a20ce95994187861f0c3227a3a8e99a73a3b1db"},
        {200, "bfb0aa97863e797943cf7c33bb7e880bb4543f3d2703c0923c6901c2af57b890"},
        {256, "dc924469b334aed2a19fac7252e9961aea41f8d91996366029dbe0884229bf36"},
    };
    for (const auto& v : vecs) {
        std::vector<uint8_t> in(v.len);
        for (std::size_t i = 0; i < v.len; ++i) in[i] = static_cast<uint8_t>(i & 0xff);
        auto r = crypto::hash::Keccak256::digest(in);
        CHECK_OK(r);
        CHECK(r.value().to_hex() == v.hex);
    }
}

// Keccak rate-boundary guard: the absorb/pad logic is most fragile at the
// 136-byte rate boundary. Adjacent lengths must hash distinctly and stably
// (a padding/boundary bug typically collides or mis-sizes here).
TEST("evm/keccak256/rate-boundary") {
    auto h = [](std::size_t n) {
        std::string s(n, 'x');
        return crypto::hash::Keccak256::digest(s).value().to_hex();
    };
    std::string a = h(135), b = h(136), c = h(137);  // rate = 136
    CHECK(a.size() == 64 && b.size() == 64 && c.size() == 64);
    CHECK(a != b && b != c && a != c);
    CHECK(h(136) == b);  // deterministic across the boundary
}

#ifdef CRYPTOLIB_HAS_SECP256K1
// ── secp256k1 ────────────────────────────────────────────────────────────────
using crypto::ec::Secp256k1;

TEST("secp256k1/pubkey/generator-point-KAT") {
    // sk = 1 → public key is the secp256k1 generator point G (uncompressed).
    std::vector<uint8_t> sk(32, 0);
    sk[31] = 1;
    auto r = Secp256k1::public_key(sk, /*compressed=*/false);
    CHECK_OK(r);
    CHECK(r.value().to_hex() ==
          "0479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
          "483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8");
}

TEST("secp256k1/pubkey/compressed-prefix") {
    std::vector<uint8_t> sk(32, 0);
    sk[31] = 1;
    auto c = Secp256k1::public_key(sk, /*compressed=*/true);
    CHECK_OK(c);
    CHECK(c.value().size() == 33);
    // G.y is even → compressed prefix 0x02.
    CHECK(c.value().to_hex().substr(0, 2) == "02");
}

TEST("secp256k1/sign-verify-roundtrip") {
    auto kp = Secp256k1::generate_keypair();
    std::vector<uint8_t> digest(32, 0xAB);
    auto sig = Secp256k1::sign(digest, kp.secret_key.span());
    CHECK_OK(sig);
    CHECK(sig.value().size() == 65);  // r ‖ s ‖ recid
    // verify takes the 64-byte r‖s (drop the recovery id).
    std::vector<uint8_t> sig64(sig.value().data(), sig.value().data() + 64);
    CHECK(Secp256k1::verify(digest, sig64, kp.public_key.span()));
}

TEST("secp256k1/sign-deterministic-rfc6979") {
    auto kp = Secp256k1::generate_keypair();
    std::vector<uint8_t> digest(32, 0x11);
    auto a = Secp256k1::sign(digest, kp.secret_key.span());
    auto b = Secp256k1::sign(digest, kp.secret_key.span());
    CHECK_OK(a); CHECK_OK(b);
    CHECK(a.value().to_hex() == b.value().to_hex());  // RFC6979 → identical
}

TEST("secp256k1/verify-rejects-tampered-digest") {
    auto kp = Secp256k1::generate_keypair();
    std::vector<uint8_t> digest(32, 0x22);
    auto sig = Secp256k1::sign(digest, kp.secret_key.span());
    CHECK_OK(sig);
    std::vector<uint8_t> sig64(sig.value().data(), sig.value().data() + 64);
    std::vector<uint8_t> wrong(32, 0x23);
    CHECK(!Secp256k1::verify(wrong, sig64, kp.public_key.span()));
}

TEST("secp256k1/recover-matches-signer") {
    auto kp = Secp256k1::generate_keypair();
    std::vector<uint8_t> digest(32, 0x42);
    auto sig = Secp256k1::sign(digest, kp.secret_key.span());  // 65-byte recoverable
    CHECK_OK(sig);
    auto rec = Secp256k1::recover(digest, sig.value().span());
    CHECK_OK(rec);
    // Recovered uncompressed pubkey must equal the signer's pubkey (ecrecover).
    CHECK(rec.value().to_hex() == kp.public_key.to_hex());
}

TEST("secp256k1/recover-wrong-digest-differs") {
    auto kp = Secp256k1::generate_keypair();
    std::vector<uint8_t> digest(32, 0x42);
    auto sig = Secp256k1::sign(digest, kp.secret_key.span());
    CHECK_OK(sig);
    std::vector<uint8_t> other(32, 0x43);
    auto rec = Secp256k1::recover(other, sig.value().span());
    // Either recovery fails or yields a different (wrong) key — never the signer.
    if (rec.is_ok()) CHECK(rec.value().to_hex() != kp.public_key.to_hex());
}

TEST("secp256k1/rejects-bad-lengths") {
    std::vector<uint8_t> short_sk(31, 1);
    CHECK(Secp256k1::public_key(short_sk, false).is_err());
    std::vector<uint8_t> sk(32, 0); sk[31] = 1;
    std::vector<uint8_t> bad_digest(31, 0);
    CHECK(Secp256k1::sign(bad_digest, sk).is_err());
}
#endif // CRYPTOLIB_HAS_SECP256K1

void run_tests_evm_btc() {
    RUN("evm/keccak256/empty-KAT");
    RUN("evm/keccak256/abc-KAT");
    RUN("evm/keccak256/multi-block");
    RUN("btc/ripemd160/empty-KAT");
    RUN("btc/ripemd160/abc-KAT");
    RUN("btc/ripemd160/million-a-prefix");
#ifdef CRYPTOLIB_HAS_OPENSSL
    RUN("btc/ripemd160/differential-vs-openssl");
#endif
    RUN("evm/keccak256/multi-length-KAT");
    RUN("evm/keccak256/rate-boundary");
#ifdef CRYPTOLIB_HAS_SECP256K1
    RUN("secp256k1/pubkey/generator-point-KAT");
    RUN("secp256k1/pubkey/compressed-prefix");
    RUN("secp256k1/sign-verify-roundtrip");
    RUN("secp256k1/sign-deterministic-rfc6979");
    RUN("secp256k1/verify-rejects-tampered-digest");
    RUN("secp256k1/recover-matches-signer");
    RUN("secp256k1/recover-wrong-digest-differs");
    RUN("secp256k1/rejects-bad-lengths");
#endif
}
