part of '../../cryptolib.dart';

typedef _BbsProofGenWithNymC =
    CryptoBufferResult Function(
      Pointer<Uint8>,
      Size,
      Pointer<Uint8>,
      Size,
      Pointer<Uint8>,
      Size,
      Pointer<Uint8>,
      Size,
      Pointer<Uint8>,
      Size,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      Size,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      Size,
      Pointer<Uint8>,
      Size,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      Size,
      Pointer<Uint64>,
      Size,
      Pointer<Uint64>,
      Size,
      Pointer<CryptoBuffer>,
    );
typedef _BbsProofGenWithNymDart =
    CryptoBufferResult Function(
      Pointer<Uint8>,
      int,
      Pointer<Uint8>,
      int,
      Pointer<Uint8>,
      int,
      Pointer<Uint8>,
      int,
      Pointer<Uint8>,
      int,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      int,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      int,
      Pointer<Uint8>,
      int,
      Pointer<Pointer<Uint8>>,
      Pointer<Size>,
      int,
      Pointer<Uint64>,
      int,
      Pointer<Uint64>,
      int,
      Pointer<CryptoBuffer>,
    );
