part of '../web_platform.dart';

final Map<String, Function> _registry32 = {
  'cryptolib_bbs_proof_gen_with_pseudonym':
      (
        Pointer<NativeType> pk,
        int pkLen,
        Pointer<NativeType> signature,
        int sigLen,
        Pointer<NativeType> header,
        int headerLen,
        Pointer<NativeType> ph,
        int phLen,
        Pointer<NativeType> contextId,
        int ctxLen,
        Pointer<NativeType> signerMsgs,
        Pointer<NativeType> signerLens,
        int signerCount,
        Pointer<NativeType> committedMsgs,
        Pointer<NativeType> committedLens,
        int committedCount,
        Pointer<NativeType> secretProverBlind,
        int spbLen,
        Pointer<NativeType> nymSecrets,
        Pointer<NativeType> nymLens,
        int nymCount,
        Pointer<NativeType> disclosedSignerIndexes,
        int disclosedSignerCount,
        Pointer<NativeType> disclosedCommittedIndexes,
        int disclosedCommittedCount,
        Pointer<NativeType> pseudonymOut,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_bbs_proof_gen_with_pseudonym',
        [
          pk.address.toJS,
          pkLen.toJS,
          signature.address.toJS,
          sigLen.toJS,
          header.address.toJS,
          headerLen.toJS,
          ph.address.toJS,
          phLen.toJS,
          contextId.address.toJS,
          ctxLen.toJS,
          signerMsgs.address.toJS,
          signerLens.address.toJS,
          signerCount.toJS,
          committedMsgs.address.toJS,
          committedLens.address.toJS,
          committedCount.toJS,
          secretProverBlind.address.toJS,
          spbLen.toJS,
          nymSecrets.address.toJS,
          nymLens.address.toJS,
          nymCount.toJS,
          disclosedSignerIndexes.address.toJS,
          disclosedSignerCount.toJS,
          disclosedCommittedIndexes.address.toJS,
          disclosedCommittedCount.toJS,
          pseudonymOut.address.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
};
