part of '../web_platform.dart';

final Map<String, Function> _registry34 = {
  'cryptolib_bbs_blind_sign':
      (
        Pointer<NativeType> sk,
        int skLen,
        Pointer<NativeType> pk,
        int pkLen,
        Pointer<NativeType> commitmentWithProof,
        int commitLen,
        Pointer<NativeType> header,
        int headerLen,
        Pointer<NativeType> msgs,
        Pointer<NativeType> msgLens,
        int msgCount,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_bbs_blind_sign',
        [
          sk.address.toJS,
          skLen.toJS,
          pk.address.toJS,
          pkLen.toJS,
          commitmentWithProof.address.toJS,
          commitLen.toJS,
          header.address.toJS,
          headerLen.toJS,
          msgs.address.toJS,
          msgLens.address.toJS,
          msgCount.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
  'cryptolib_bbs_verify_blind_sign':
      (
        Pointer<NativeType> pk,
        int pkLen,
        Pointer<NativeType> signature,
        int sigLen,
        Pointer<NativeType> header,
        int headerLen,
        Pointer<NativeType> msgs,
        Pointer<NativeType> msgLens,
        int msgCount,
        Pointer<NativeType> committedMsgs,
        Pointer<NativeType> committedLens,
        int committedCount,
        Pointer<NativeType> secretProverBlind,
        int spbLen,
      ) => WebEngine.current.callInt('_cbw_cryptolib_bbs_verify_blind_sign', [
        pk.address.toJS,
        pkLen.toJS,
        signature.address.toJS,
        sigLen.toJS,
        header.address.toJS,
        headerLen.toJS,
        msgs.address.toJS,
        msgLens.address.toJS,
        msgCount.toJS,
        committedMsgs.address.toJS,
        committedLens.address.toJS,
        committedCount.toJS,
        secretProverBlind.address.toJS,
        spbLen.toJS,
      ]),
  'cryptolib_bbs_hash_to_scalar':
      (
        Pointer<NativeType> msg,
        int msgLen,
        Pointer<NativeType> dst,
        int dstLen,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_bbs_hash_to_scalar',
        [msg.address.toJS, msgLen.toJS, dst.address.toJS, dstLen.toJS],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
  'cryptolib_bbs_random_scalar': () => WebEngine.current.callStruct(
    '_cbw_cryptolib_bbs_random_scalar',
    [],
    CipherBirdBufferResult.size,
    CipherBirdBufferResult._new,
  ),
};
