part of '../web_platform.dart';

final Map<String, Function> _registry30 = {
  'cryptolib_bbs_proof_gen':
      (
        Pointer<NativeType> pk,
        int pkLen,
        Pointer<NativeType> signature,
        int sigLen,
        Pointer<NativeType> header,
        int headerLen,
        Pointer<NativeType> ph,
        int phLen,
        Pointer<NativeType> msgs,
        Pointer<NativeType> msgLens,
        int msgCount,
        Pointer<NativeType> disclosedIndexes,
        int disclosedCount,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_bbs_proof_gen',
        [
          pk.address.toJS,
          pkLen.toJS,
          signature.address.toJS,
          sigLen.toJS,
          header.address.toJS,
          headerLen.toJS,
          ph.address.toJS,
          phLen.toJS,
          msgs.address.toJS,
          msgLens.address.toJS,
          msgCount.toJS,
          disclosedIndexes.address.toJS,
          disclosedCount.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
  'cryptolib_bbs_proof_verify':
      (
        Pointer<NativeType> pk,
        int pkLen,
        Pointer<NativeType> proof,
        int proofLen,
        Pointer<NativeType> header,
        int headerLen,
        Pointer<NativeType> ph,
        int phLen,
        Pointer<NativeType> disclosedMsgs,
        Pointer<NativeType> disclosedLens,
        int disclosedCount,
        Pointer<NativeType> disclosedIndexes,
        int indexesCount,
      ) => WebEngine.current.callInt('_cbw_cryptolib_bbs_proof_verify', [
        pk.address.toJS,
        pkLen.toJS,
        proof.address.toJS,
        proofLen.toJS,
        header.address.toJS,
        headerLen.toJS,
        ph.address.toJS,
        phLen.toJS,
        disclosedMsgs.address.toJS,
        disclosedLens.address.toJS,
        disclosedCount.toJS,
        disclosedIndexes.address.toJS,
        indexesCount.toJS,
      ]),
  'cryptolib_bbs_commit_with_nym':
      (
        Pointer<NativeType> committedMsgs,
        Pointer<NativeType> committedLens,
        int committedCount,
        Pointer<NativeType> proverNyms,
        Pointer<NativeType> nymLens,
        int nymCount,
        Pointer<NativeType> secretProverBlind,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_bbs_commit_with_nym',
        [
          committedMsgs.address.toJS,
          committedLens.address.toJS,
          committedCount.toJS,
          proverNyms.address.toJS,
          nymLens.address.toJS,
          nymCount.toJS,
          secretProverBlind.address.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
};
