part of '../web_platform.dart';

final Map<String, Function> _registry37 = {
  'cryptolib_opaque_server_respond':
      (
        Pointer<NativeType> context,
        int contextLen,
        Pointer<NativeType> serverPrivateKey,
        int skLen,
        Pointer<NativeType> serverPublicKey,
        int pkLen,
        Pointer<NativeType> record,
        int recordLen,
        Pointer<NativeType> credentialIdentifier,
        int ciLen,
        Pointer<NativeType> oprfSeed,
        int seedLen,
        Pointer<NativeType> ke1,
        int ke1Len,
        Pointer<NativeType> serverIdentity,
        int sidLen,
        Pointer<NativeType> clientIdentity,
        int cidLen,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_opaque_server_respond',
        [
          context.address.toJS,
          contextLen.toJS,
          serverPrivateKey.address.toJS,
          skLen.toJS,
          serverPublicKey.address.toJS,
          pkLen.toJS,
          record.address.toJS,
          recordLen.toJS,
          credentialIdentifier.address.toJS,
          ciLen.toJS,
          oprfSeed.address.toJS,
          seedLen.toJS,
          ke1.address.toJS,
          ke1Len.toJS,
          serverIdentity.address.toJS,
          sidLen.toJS,
          clientIdentity.address.toJS,
          cidLen.toJS,
        ],
        CipherBirdOpaqueKe2.size,
        CipherBirdOpaqueKe2._new,
      ),
  'cryptolib_opaque_client_finish':
      (
        Pointer<NativeType> clientState,
        int csLen,
        Pointer<NativeType> ke2,
        int ke2Len,
        Pointer<NativeType> context,
        int contextLen,
        Pointer<NativeType> serverIdentity,
        int sidLen,
        Pointer<NativeType> clientIdentity,
        int cidLen,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_opaque_client_finish',
        [
          clientState.address.toJS,
          csLen.toJS,
          ke2.address.toJS,
          ke2Len.toJS,
          context.address.toJS,
          contextLen.toJS,
          serverIdentity.address.toJS,
          sidLen.toJS,
          clientIdentity.address.toJS,
          cidLen.toJS,
        ],
        CipherBirdOpaqueKe3.size,
        CipherBirdOpaqueKe3._new,
      ),
  'cryptolib_opaque_server_finish':
      (
        Pointer<NativeType> serverState,
        int ssLen,
        Pointer<NativeType> ke3,
        int ke3Len,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_opaque_server_finish',
        [serverState.address.toJS, ssLen.toJS, ke3.address.toJS, ke3Len.toJS],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
};
