part of '../web_platform.dart';

final Map<String, Function> _registry25 = {
  'cryptolib_frost_sign':
      (
        int identifier,
        Pointer<NativeType> shareSecret,
        int skLen,
        Pointer<NativeType> groupPublicKey,
        int gpkLen,
        Pointer<NativeType> hidingNonce,
        int hnLen,
        Pointer<NativeType> bindingNonce,
        int bnLen,
        Pointer<NativeType> msg,
        int msgLen,
        Pointer<NativeType> ids,
        Pointer<NativeType> hidingCommits,
        Pointer<NativeType> bindingCommits,
        int count,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_frost_sign',
        [
          identifier.toJS,
          shareSecret.address.toJS,
          skLen.toJS,
          groupPublicKey.address.toJS,
          gpkLen.toJS,
          hidingNonce.address.toJS,
          hnLen.toJS,
          bindingNonce.address.toJS,
          bnLen.toJS,
          msg.address.toJS,
          msgLen.toJS,
          ids.address.toJS,
          hidingCommits.address.toJS,
          bindingCommits.address.toJS,
          count.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
  'cryptolib_frost_aggregate':
      (
        Pointer<NativeType> groupPublicKey,
        int gpkLen,
        Pointer<NativeType> msg,
        int msgLen,
        Pointer<NativeType> ids,
        Pointer<NativeType> hidingCommits,
        Pointer<NativeType> bindingCommits,
        int count,
        Pointer<NativeType> sigShares,
      ) => WebEngine.current.callStruct(
        '_cbw_cryptolib_frost_aggregate',
        [
          groupPublicKey.address.toJS,
          gpkLen.toJS,
          msg.address.toJS,
          msgLen.toJS,
          ids.address.toJS,
          hidingCommits.address.toJS,
          bindingCommits.address.toJS,
          count.toJS,
          sigShares.address.toJS,
        ],
        CipherBirdBufferResult.size,
        CipherBirdBufferResult._new,
      ),
  'cryptolib_frost_verify':
      (
        Pointer<NativeType> msg,
        int msgLen,
        Pointer<NativeType> sig,
        int sigLen,
        Pointer<NativeType> groupPublicKey,
        int gpkLen,
      ) => WebEngine.current.callInt('_cbw_cryptolib_frost_verify', [
        msg.address.toJS,
        msgLen.toJS,
        sig.address.toJS,
        sigLen.toJS,
        groupPublicKey.address.toJS,
        gpkLen.toJS,
      ]),
};
