part of '../web_platform.dart';

/// Every C ABI symbol, as the Dart closure `lookupFunction` returns.
final Map<String, Function> symbolRegistry = {
  ..._registry01,
  ..._registry02,
  ..._registry03,
  ..._registry04,
  ..._registry05,
  ..._registry06,
  ..._registry07,
  ..._registry08,
  ..._registry09,
  ..._registry10,
  ..._registry11,
  ..._registry12,
  ..._registry13,
  ..._registry14,
  ..._registry15,
  ..._registry16,
  ..._registry17,
  ..._registry18,
  ..._registry19,
  ..._registry20,
  ..._registry21,
  ..._registry22,
  ..._registry23,
  ..._registry24,
  ..._registry25,
  ..._registry26,
  ..._registry27,
  ..._registry28,
  ..._registry29,
  ..._registry30,
  ..._registry31,
  ..._registry32,
  ..._registry33,
  ..._registry34,
  ..._registry35,
  ..._registry36,
  ..._registry37,
  ..._registry38,
  ..._registry39,
  ..._registry40,
  ..._registry41,
  ..._registry42,
  ..._registry43,
};
