#!/usr/bin/env python3
"""Extract a curated subset of official post-quantum known-answer vectors into a
committed C++ header (pqc_kat_vectors.hpp).

Provenance — all vectors are official, not synthesized:
  * NIST ACVP (FIPS 203 / 204 / 205) "internalProjection" test vectors, as
    vendored by liboqs. These are the exact vectors liboqs validates itself
    against, so consuming them through our wrapper proves the wrapper passes
    bytes across the FFI boundary without corruption (right level, right
    encoding, no truncation) — the layer we actually wrote.

We pick a small mix of accept/reject cases per algorithm so the header stays a
reasonable size (SLH-DSA signatures alone are ~17 KB each) while still exercising
both the "valid signature verifies" and "tampered/short signature is rejected"
paths, plus non-empty domain-separation contexts.

Regenerate:
  python3 tests/vectors/extract_pqc_kat.py [LIBOQS_ACVP_DIR] > tests/vectors/pqc_kat_vectors.hpp
Default LIBOQS_ACVP_DIR is the Homebrew liboqs 0.15.0 share path.
"""
import json
import os
import sys

DEFAULT_ACVP = "/opt/homebrew/Cellar/liboqs/0.15.0/share/liboqs/tests/ACVP_Vectors"

# Curated tcIds per algorithm/parameter set (accept + reject mix, small messages
# preferred to bound header size).
ML_KEM_DECAP_TCS = None          # None => take first 3 of the decapsulation group
ML_DSA_SIGVER_TCS = [35, 37, 31, 42, 41, 44]     # 3 valid, 3 invalid
SLH_DSA_SIGVER_TCS = [9, 12, 1]                   # 1 valid, 2 invalid (modified, too-small)


def load(acvp, name):
    with open(os.path.join(acvp, name, "internalProjection.json")) as f:
        return json.load(f)


def group(doc, param, func=None):
    for g in doc["testGroups"]:
        if g.get("parameterSet") != param:
            continue
        if func is not None and g.get("function") != func:
            continue
        return g
    raise SystemExit("group not found: %s / %s" % (param, func))


def pick(g, tcs):
    if tcs is None:
        return g["tests"][:3]
    by_id = {t["tcId"]: t for t in g["tests"]}
    return [by_id[i] for i in tcs]


def hexval(t, *keys):
    for k in keys:
        if k in t and t[k] is not None:
            return t[k]
    return ""


def emit_kem(g, tests):
    out = ["inline constexpr KemDecapVec ml_kem_768_decap[] = {"]
    for t in tests:
        out.append('  { %d,\n    "%s",\n    "%s",\n    "%s" },'
                    % (t["tcId"], t["dk"], t["c"], t["k"]))
    out.append("};")
    return "\n".join(out)


def emit_sigver(name, g, tests):
    out = ["inline constexpr SigVerVec %s[] = {" % name]
    for t in tests:
        out.append('  { %d, %s,\n    "%s",\n    "%s",\n    "%s",\n    "%s" },'
                    % (t["tcId"], "true" if t["testPassed"] else "false",
                       t["pk"], hexval(t, "message"), hexval(t, "context"), t["signature"]))
    out.append("};")
    return "\n".join(out)


def main():
    acvp = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ACVP

    kem = load(acvp, "ML-KEM-encapDecap-FIPS203")
    mldsa = load(acvp, "ML-DSA-sigVer-FIPS204")
    slhdsa = load(acvp, "SLH-DSA-sigVer-FIPS205")

    kem_g = group(kem, "ML-KEM-768", func="decapsulation")
    mldsa_g = group(mldsa, "ML-DSA-65")
    slhdsa_g = group(slhdsa, "SLH-DSA-SHA2-128f")

    print("// clang-format off")
    print("#pragma once")
    print("// ─────────────────────────────────────────────────────────────────────────")
    print("// AUTO-GENERATED by tests/vectors/extract_pqc_kat.py — DO NOT EDIT BY HAND.")
    print("//")
    print("// Official post-quantum known-answer vectors (not synthesized):")
    print("//   * NIST ACVP FIPS 203 / 204 / 205 internalProjection, vendored by liboqs.")
    print("//   * ML-KEM-768 decapsulation, ML-DSA-65 sigVer, SLH-DSA-SHA2-128f sigVer.")
    print("// A curated accept/reject mix; see the extractor for provenance and rationale.")
    print("// ─────────────────────────────────────────────────────────────────────────")
    print("#include <string_view>")
    print("")
    print("namespace kat::pqc {")
    print("")
    print("struct KemDecapVec { int tc; std::string_view dk_hex, c_hex, k_hex; };")
    print("// expect_valid: whether verify() must ACCEPT (true) or REJECT (false).")
    print("struct SigVerVec { int tc; bool expect_valid;")
    print("                   std::string_view pk_hex, msg_hex, ctx_hex, sig_hex; };")
    print("")
    print(emit_kem(kem_g, pick(kem_g, ML_KEM_DECAP_TCS)))
    print("")
    print(emit_sigver("ml_dsa_65_sigver", mldsa_g, pick(mldsa_g, ML_DSA_SIGVER_TCS)))
    print("")
    print(emit_sigver("slh_dsa_128f_sigver", slhdsa_g, pick(slhdsa_g, SLH_DSA_SIGVER_TCS)))
    print("")
    print("} // namespace kat::pqc")
    print("// clang-format on")


if __name__ == "__main__":
    main()
